engine:
  - changed-files:
    - any-glob-to-any-file: 'src/engine/gameEngine.ts'

ai:
  - changed-files:
    - any-glob-to-any-file: 'src/engine/aiEngine.ts'

ui:
  - changed-files:
    - any-glob-to-any-file: 'src/components/**'

utils:
  - changed-files:
    - any-glob-to-any-file: 'src/utils/**'

assets:
  - changed-files:
    - any-glob-to-any-file: 'assets/**'

config:
  - changed-files:
    - any-glob-to-any-file:
      - 'app.json'
      - 'eas.json'
      - 'tsconfig.json'
      - 'package.json'
      - '.github/**'
